name: backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.0.2
  - pytest  # dev
  - mypy  # dev
  - coverage  # dev
  - types-requests  # dev
  - requests=2.23.0
  - tqdm
  - requests
  - textacy
  - spacy
  - pip:
    - pyzipper
    - bs4==0.0.1
    - git+https://github.com/w2sv/Lingularity-Backend.git
